### ISSUE TITLE
Add test for rust-lang/rust#80127

### ISSUE THREAD

**Issue by bjorn3** [Gankra/abi-cafe#15]
https://github.com/rust-lang/rust/issues/80127 is an issue where stack arguments with a 16-byte alignment are passed at the wrong offset.

**Comment by Gankra** [comment]
As of #20:

* `@align 16` is ostensibly supported in kdl-script, the new test format
  * the rust backend knows how to generate it, although I haven't actually tested it
  * the C backend doesn't know how to generate it, and will skip if it sees any attrs, but we could add it

**Comment by Gankra** [comment]
Filed https://github.com/Gankra/abi-cafe/issues/26 for the main blocker
