### ISSUE TITLE
Test for `f128`

### ISSUE THREAD

**Issue by tgross35** [Gankra/abi-cafe#16]
Is a test for `f128` possible? To check GCC `__float128` against LLVM's `fp128`

**Comment by Gankra** [comment]
Oh rad, thank you for letting me know about these!

Apologies for the radio silence, I just finished rewriting all of abi-cafe to make adding new stuff way easier >.>;

**Comment by tgross35** [comment]
That is awesome! We have both f16 and f128 available unstably which could be checked against `_Float16` and `_Float128`/`__float128`. These come with a handful of known ABI issues already https://github.com/rust-lang/rust/issues/116909#issuecomment-1969554030

Any chance you are planning to upstream this in to Rust's CI somehow? I know there has been a lot of interest, just nobody has figured out how to do the work.

**Comment by Gankra** [comment]
Notes on adding support for these types:

First off, the type system already contains them, everything just refuses to implement them.

# Adding to rust

There are two parts to support: teaching the rust backend to generate the values, and teaching it to detect that the test uses f128/f16, and emitting a feature gate/nightly check, similar to vectorcall.

## Teaching to use the values/types

https://github.com/Gankra/abi-cafe/blob/6ba68656bd74d05692e3abb83a51a0bfc2b7ce32/src/abis/rust/declare.rs#L79-L92

https://github.com/Gankra/abi-cafe/blob/6ba68656bd74d05692e3abb83a51a0bfc2b7ce32/src/abis/rust/init.rs#L34-L49

## Detecting the feature

Kinda spaghetti for vectorcall here. Detecting f16/f128 usage is also a bit harder.

https://github.com/Gankra/abi-cafe/blob/6ba68656bd74d05692e3abb83a51a0bfc2b7ce32/src/abis/rust/write.rs#L18-L20

https://github.com/Gankra/abi-cafe/blob/6ba68656bd74d05692e3abb83a51a0bfc2b7ce32/src/abis/rust/declare.rs#L451-L456

You could maybe just do a prepass on the definitions list to sniff for those types?

https://github.com/Gankra/abi-cafe/blob/6ba68656bd74d05692e3abb83a51a0bfc2b7ce32/src/abis/rust/declare.rs#L30-L40


# Adding to C

Essentially the exact same thing as Rust, but less "detecting nightly and setting feature-gates" and more "detecting C toolchain, emitting toolchain-specific code". See for example where convention attributes get processed:

https://github.com/Gankra/abi-cafe/blob/6ba68656bd74d05692e3abb83a51a0bfc2b7ce32/src/abis/c/declare.rs#L481-L492
