### ISSUE TITLE
Add test for rust-lang/rust#122767

### ISSUE THREAD

**Issue by cuviper** [Gankra/abi-cafe#23]
In rust-lang/rust#122767, ppc64le was found to have a mismatched ABI on this struct:

```rust
#[repr(C)]
#[repr(align(16))]
pub struct TwoU64s {
    pub a: u64,
    pub b: u64,
}
```

Rust was passing this like `[2 x i64]`, while Clang passes `[1 x i128]` -- notably, it's not bare `i128` either.

**Comment by Gankra** [comment]
I believe this would be `TwoU64s.procgen.kdl`:

```
@align 16
struct "TwoU64s" {
    a "u64"
    b "u64"
}
```

Although see https://github.com/Gankra/abi-cafe/issues/15#issuecomment-2198688511 for caveats on align not being fully implemented/tested yet.

**Comment by Gankra** [comment]
Filed https://github.com/Gankra/abi-cafe/issues/26 for the main blocker
